<a href="https://colab.research.google.com/github/patel7147/ROYAL_DL/blob/master/DataInsurance_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import numpy as np
import pandas as pd
from keras.utils import to_categorical

Pandas is used for data manipulation in the given dataset

In [157]:
dataset = pd.read_csv('/content/datasets_13720_18513_insurance.csv')
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [184]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['sex'] = le.fit_transform(dataset['sex'])
dataset['smoker'] = le.fit_transform(dataset['smoker'])
dataset['region'] = le.fit_transform(dataset['region'])
dataset['age'] = (dataset['age']-dataset['age'].mean())/dataset['age'].max()
dataset['sex'] = (dataset['sex']-dataset['sex'].mean())/dataset['sex'].max()
dataset['bmi'] = (dataset['bmi']-dataset['bmi'].mean())/dataset['bmi'].max()
dataset['children'] = (dataset['children']-dataset['children'].mean())/dataset['children'].max()
dataset['smoker'] = (dataset['smoker']-dataset['smoker'].mean())/dataset['smoker'].max()
dataset['region'] = (dataset['region']-dataset['region'].mean())/dataset['region'].max()
dataset['charges'] = (dataset['charges']-dataset['charges'].mean())/dataset['charges'].max()

x = dataset.iloc[:,:5].values
y = dataset.iloc[:,6].values

In [314]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1070, 5)
(1070,)
(268, 5)
(268,)

In [330]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam

model = Sequential()

model.add(Dense(300, input_shape=(5,),activation='softmax'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(1,activation='linear'))

model.compile(Adam(lr=0.1),'mean_squared_error',metrics=['mse'])

model.summary()

Model: "sequential_82"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_352 (Dense)            (None, 300)               1800
_________________________________________________________________
dense_353 (Dense)            (None, 100)               30100
_________________________________________________________________
dense_354 (Dense)            (None, 100)               10100
_________________________________________________________________
dense_355 (Dense)            (None, 1)                 101
=================================================================
Total params: 42,101
Trainable params: 42,101
Non-trainable params: 0
_________________________________________________________________

In [331]:
model.fit(x_train,y_train,epochs=100)
y_pred = model.predict(x_test)

Epoch 1/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9916 - mse: 0.9916
Epoch 2/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9826 - mse: 0.9826
Epoch 3/100
34/34 [==============================] - 0s 2ms/step - loss: 1.0014 - mse: 1.0014
Epoch 4/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9867 - mse: 0.9867
Epoch 5/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9823 - mse: 0.9823
Epoch 6/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9852 - mse: 0.9852
Epoch 7/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9836 - mse: 0.9836
Epoch 8/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9795 - mse: 0.9795
Epoch 9/100
34/34 [==============================] - 0s 2ms/step - loss: 0.5030 - mse: 0.5030
Epoch 10/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2878 - mse: 0.2878
Epoch 11/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2066 - mse: 0.2066
Epoch 12/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2065 - mse: 0.2065
Epoch 13/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1880 - mse: 0.1880
Epoch 14/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1850 - mse: 0.1850
Epoch 15/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1880 - mse: 0.1880
Epoch 16/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1827 - mse: 0.1827
Epoch 17/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1854 - mse: 0.1854
Epoch 18/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1699 - mse: 0.1699
Epoch 19/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1922 - mse: 0.1922
Epoch 20/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1937 - mse: 0.1937
Epoch 21/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1785 - mse: 0.1785
Epoch 22/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1736 - mse: 0.1736
Epoch 23/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1880 - mse: 0.1880
Epoch 24/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1760 - mse: 0.1760
Epoch 25/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1687 - mse: 0.1687
Epoch 26/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1676 - mse: 0.1676
Epoch 27/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1620 - mse: 0.1620
Epoch 28/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1695 - mse: 0.1695
Epoch 29/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1652 - mse: 0.1652
Epoch 30/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1892 - mse: 0.1892
Epoch 31/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1698 - mse: 0.1698
Epoch 32/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1701 - mse: 0.1701
Epoch 33/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1789 - mse: 0.1789
Epoch 34/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1707 - mse: 0.1707
Epoch 35/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1734 - mse: 0.1734
Epoch 36/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1790 - mse: 0.1790
Epoch 37/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1756 - mse: 0.1756
Epoch 38/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1659 - mse: 0.1659
Epoch 39/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1743 - mse: 0.1743
Epoch 40/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1694 - mse: 0.1694
Epoch 41/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1699 - mse: 0.1699
Epoch 42/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1802 - mse: 0.1802
Epoch 43/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1707 - mse: 0.1707
Epoch 44/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1772 - mse: 0.1772
Epoch 45/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1747 - mse: 0.1747
Epoch 46/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1745 - mse: 0.1745
Epoch 47/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1860 - mse: 0.1860
Epoch 48/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1715 - mse: 0.1715
Epoch 49/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1692 - mse: 0.1692
Epoch 50/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1823 - mse: 0.1823
Epoch 51/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1762 - mse: 0.1762
Epoch 52/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1977 - mse: 0.1977
Epoch 53/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1762 - mse: 0.1762
Epoch 54/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1770 - mse: 0.1770
Epoch 55/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1756 - mse: 0.1756
Epoch 56/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1754 - mse: 0.1754
Epoch 57/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1811 - mse: 0.1811
Epoch 58/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1797 - mse: 0.1797
Epoch 59/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1929 - mse: 0.1929
Epoch 60/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1914 - mse: 0.1914
Epoch 61/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1948 - mse: 0.1948
Epoch 62/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1938 - mse: 0.1938
Epoch 63/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1807 - mse: 0.1807
Epoch 64/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1785 - mse: 0.1785
Epoch 65/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2345 - mse: 0.2345
Epoch 66/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2297 - mse: 0.2297
Epoch 67/100
34/34 [==============================] - 0s 3ms/step - loss: 0.2125 - mse: 0.2125
Epoch 68/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1955 - mse: 0.1955
Epoch 69/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1765 - mse: 0.1765
Epoch 70/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1750 - mse: 0.1750
Epoch 71/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1780 - mse: 0.1780
Epoch 72/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1930 - mse: 0.1930
Epoch 73/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1776 - mse: 0.1776
Epoch 74/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1793 - mse: 0.1793
Epoch 75/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1771 - mse: 0.1771
Epoch 76/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2006 - mse: 0.2006
Epoch 77/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2019 - mse: 0.2019
Epoch 78/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1942 - mse: 0.1942
Epoch 79/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1984 - mse: 0.1984
Epoch 80/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1767 - mse: 0.1767
Epoch 81/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1750 - mse: 0.1750
Epoch 82/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1714 - mse: 0.1714
Epoch 83/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2091 - mse: 0.2091
Epoch 84/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2446 - mse: 0.2446
Epoch 85/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2174 - mse: 0.2174
Epoch 86/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2045 - mse: 0.2045
Epoch 87/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2065 - mse: 0.2065
Epoch 88/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1917 - mse: 0.1917
Epoch 89/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2114 - mse: 0.2114
Epoch 90/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2061 - mse: 0.2061
Epoch 91/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1928 - mse: 0.1928
Epoch 92/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1879 - mse: 0.1879
Epoch 93/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2001 - mse: 0.2001
Epoch 94/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1911 - mse: 0.1911
Epoch 95/100
34/34 [==============================] - 0s 2ms/step - loss: 0.1947 - mse: 0.1947
Epoch 96/100
34/34 [==============================] - 0s 2ms/step - loss: 0.2152 - mse: 0.2152
Epoch 97/100
34/34 [==============================] - 0s 3ms/step - loss: 0.2037 - mse: 0.2037
Epoch 98/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1942 - mse: 0.1942
Epoch 99/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1913 - mse: 0.1913
Epoch 100/100
34/34 [==============================] - 0s 3ms/step - loss: 0.1921 - mse: 0.1921

In [332]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_pred,y_test))

0.1771512118256706

The minimum error is 0.17