<a href="https://colab.research.google.com/github/patel7147/ROYAL_DL/blob/master/DataInsurance_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import numpy as np
import pandas as pd
from keras.utils import to_categorical

Pandas is used for data manipulation in the given dataset

In [157]:
dataset = pd.read_csv('/content/datasets_13720_18513_insurance.csv')
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [184]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['sex'] = le.fit_transform(dataset['sex'])
dataset['smoker'] = le.fit_transform(dataset['smoker'])
dataset['region'] = le.fit_transform(dataset['region'])
dataset['age'] = (dataset['age']-dataset['age'].mean())/dataset['age'].max()
dataset['sex'] = (dataset['sex']-dataset['sex'].mean())/dataset['sex'].max()
dataset['bmi'] = (dataset['bmi']-dataset['bmi'].mean())/dataset['bmi'].max()
dataset['children'] = (dataset['children']-dataset['children'].mean())/dataset['children'].max()
dataset['smoker'] = (dataset['smoker']-dataset['smoker'].mean())/dataset['smoker'].max()
dataset['region'] = (dataset['region']-dataset['region'].mean())/dataset['region'].max()
dataset['charges'] = (dataset['charges']-dataset['charges'].mean())/dataset['charges'].max()

x = dataset.iloc[:,:5].values
y = dataset.iloc[:,6].values

In [314]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1070, 5)
(1070,)
(268, 5)
(268,)

In [327]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam

model = Sequential()

model.add(Dense(300, input_shape=(5,),activation='softmax'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(1,activation='sigmoid'))

model.compile(Adam(lr=0.1),'mean_squared_error',metrics=['mse'])

model.summary()

Model: "sequential_81"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_348 (Dense)            (None, 300)               1800
_________________________________________________________________
dense_349 (Dense)            (None, 100)               30100
_________________________________________________________________
dense_350 (Dense)            (None, 100)               10100
_________________________________________________________________
dense_351 (Dense)            (None, 1)                 101
=================================================================
Total params: 42,101
Trainable params: 42,101
Non-trainable params: 0
_________________________________________________________________

In [328]:
model.fit(x_train,y_train,epochs=100)
y_pred = model.predict(x_test)

Epoch 1/100
34/34 [==============================] - 0s 3ms/step - loss: 1.0028 - mse: 1.0028
Epoch 2/100
34/34 [==============================] - 0s 3ms/step - loss: 0.9717 - mse: 0.9717
Epoch 3/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9717 - mse: 0.9717
Epoch 4/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9716 - mse: 0.9716
Epoch 5/100
34/34 [==============================] - 0s 2ms/step - loss: 0.9715 - mse: 0.9715
Epoch 6/100
34/34 [==============================] - 0s 3ms/step - loss: 0.9715 - mse: 0.9715
Epoch 7/100
34/34 [==============================] - 0s 3ms/step - loss: 0.9543 - mse: 0.9543
Epoch 8/100
34/34 [==============================] - 0s 3ms/step - loss: 0.8547 - mse: 0.8547
Epoch 9/100
34/34 [==============================] - 0s 3ms/step - loss: 0.8264 - mse: 0.8264
Epoch 10/100
34/34 [==============================] - 0s 3ms/step - loss: 0.8094 - mse: 0.8094
Epoch 11/100
34/34 [==============================] - 0s 3ms/step - loss: 0.8098 - mse: 0.8098
Epoch 12/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7998 - mse: 0.7998
Epoch 13/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7922 - mse: 0.7922
Epoch 14/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7866 - mse: 0.7866
Epoch 15/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7898 - mse: 0.7898
Epoch 16/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7895 - mse: 0.7895
Epoch 17/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7888 - mse: 0.7888
Epoch 18/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7897 - mse: 0.7897
Epoch 19/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7905 - mse: 0.7905
Epoch 20/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7958 - mse: 0.7958
Epoch 21/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7876 - mse: 0.7876
Epoch 22/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7884 - mse: 0.7884
Epoch 23/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7861 - mse: 0.7861
Epoch 24/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7898 - mse: 0.7898
Epoch 25/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7868 - mse: 0.7868
Epoch 26/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7834 - mse: 0.7834
Epoch 27/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7810 - mse: 0.7810
Epoch 28/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7831 - mse: 0.7831
Epoch 29/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7860 - mse: 0.7860
Epoch 30/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7853 - mse: 0.7853
Epoch 31/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7812 - mse: 0.7812
Epoch 32/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7787 - mse: 0.7787
Epoch 33/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7784 - mse: 0.7784
Epoch 34/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7767 - mse: 0.7767
Epoch 35/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7760 - mse: 0.7760
Epoch 36/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7782 - mse: 0.7782
Epoch 37/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7808 - mse: 0.7808
Epoch 38/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7827 - mse: 0.7827
Epoch 39/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7836 - mse: 0.7836
Epoch 40/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7794 - mse: 0.7794
Epoch 41/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7780 - mse: 0.7780
Epoch 42/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7795 - mse: 0.7795
Epoch 43/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7782 - mse: 0.7782
Epoch 44/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7833 - mse: 0.7833
Epoch 45/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7790 - mse: 0.7790
Epoch 46/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7822 - mse: 0.7822
Epoch 47/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7788 - mse: 0.7788
Epoch 48/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7779 - mse: 0.7779
Epoch 49/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7815 - mse: 0.7815
Epoch 50/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7821 - mse: 0.7821
Epoch 51/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7797 - mse: 0.7797
Epoch 52/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7813 - mse: 0.7813
Epoch 53/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7826 - mse: 0.7826
Epoch 54/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7802 - mse: 0.7802
Epoch 55/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7787 - mse: 0.7787
Epoch 56/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7815 - mse: 0.7815
Epoch 57/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7810 - mse: 0.7810
Epoch 58/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7839 - mse: 0.7839
Epoch 59/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7859 - mse: 0.7859
Epoch 60/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7861 - mse: 0.7861
Epoch 61/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7817 - mse: 0.7817
Epoch 62/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7800 - mse: 0.7800
Epoch 63/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7770 - mse: 0.7770
Epoch 64/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7830 - mse: 0.7830
Epoch 65/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7772 - mse: 0.7772
Epoch 66/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7781 - mse: 0.7781
Epoch 67/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7748 - mse: 0.7748
Epoch 68/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7752 - mse: 0.7752
Epoch 69/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7773 - mse: 0.7773
Epoch 70/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7739 - mse: 0.7739
Epoch 71/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7761 - mse: 0.7761
Epoch 72/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7757 - mse: 0.7757
Epoch 73/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7758 - mse: 0.7758
Epoch 74/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7733 - mse: 0.7733
Epoch 75/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7753 - mse: 0.7753
Epoch 76/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7746 - mse: 0.7746
Epoch 77/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7767 - mse: 0.7767
Epoch 78/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7777 - mse: 0.7777
Epoch 79/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7746 - mse: 0.7746
Epoch 80/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7743 - mse: 0.7743
Epoch 81/100
34/34 [==============================] - 0s 2ms/step - loss: 0.7779 - mse: 0.7779
Epoch 82/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7793 - mse: 0.7793
Epoch 83/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7731 - mse: 0.7731
Epoch 84/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7739 - mse: 0.7739
Epoch 85/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7737 - mse: 0.7737
Epoch 86/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7797 - mse: 0.7797
Epoch 87/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7747 - mse: 0.7747
Epoch 88/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7733 - mse: 0.7733
Epoch 89/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7730 - mse: 0.7730
Epoch 90/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7736 - mse: 0.7736
Epoch 91/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7724 - mse: 0.7724
Epoch 92/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7737 - mse: 0.7737
Epoch 93/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7731 - mse: 0.7731
Epoch 94/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7757 - mse: 0.7757
Epoch 95/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7739 - mse: 0.7739
Epoch 96/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7749 - mse: 0.7749
Epoch 97/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7728 - mse: 0.7728
Epoch 98/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7776 - mse: 0.7776
Epoch 99/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7744 - mse: 0.7744
Epoch 100/100
34/34 [==============================] - 0s 3ms/step - loss: 0.7807 - mse: 0.7807

In [329]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_pred,y_test))

0.8708431843405964