<a href="https://colab.research.google.com/github/patel7147/ROYAL_DL/blob/master/DataInsurance_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from keras.utils import to_categorical

Pandas is used for data manipulation in the given dataset

In [2]:
dataset = pd.read_csv('/content/datasets_13720_18513_insurance.csv')
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['sex'] = le.fit_transform(dataset['sex'])
dataset['smoker'] = le.fit_transform(dataset['smoker'])
dataset['region'] = le.fit_transform(dataset['region'])
dataset['age'] = (dataset['age']-dataset['age'].mean())/dataset['age'].max()
dataset['sex'] = (dataset['sex']-dataset['sex'].mean())/dataset['sex'].max()
dataset['bmi'] = (dataset['bmi']-dataset['bmi'].mean())/dataset['bmi'].max()
dataset['children'] = (dataset['children']-dataset['children'].mean())/dataset['children'].max()
dataset['smoker'] = (dataset['smoker']-dataset['smoker'].mean())/dataset['smoker'].max()
dataset['region'] = (dataset['region']-dataset['region'].mean())/dataset['region'].max()
dataset['charges'] = (dataset['charges']-dataset['charges'].mean())/dataset['charges'].max()

x = dataset.iloc[:,:5].values
y = dataset.iloc[:,6].values

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1070, 5)
(1070,)
(268, 5)
(268,)

In [17]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam

model = Sequential()

model.add(Dense(300, input_shape=(5,),activation='relu'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(100,activation='softmax'))
model.add(Dense(1,activation='linear'))

model.compile(Adam(lr=0.001),'mean_squared_error',metrics=['mse'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_16 (Dense)             (None, 300)               1800
_________________________________________________________________
dense_17 (Dense)             (None, 100)               30100
_________________________________________________________________
dense_18 (Dense)             (None, 100)               10100
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 101
=================================================================
Total params: 42,101
Trainable params: 42,101
Non-trainable params: 0
_________________________________________________________________

In [18]:
model.fit(x_train,y_train,epochs=100)
y_pred = model.predict(x_test)

Epoch 1/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0353 - mse: 0.0353
Epoch 2/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0353 - mse: 0.0353
Epoch 3/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0351 - mse: 0.0351
Epoch 4/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0340 - mse: 0.0340
Epoch 5/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0310 - mse: 0.0310
Epoch 6/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0277 - mse: 0.0277
Epoch 7/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0245 - mse: 0.0245
Epoch 8/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0214 - mse: 0.0214
Epoch 9/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0188 - mse: 0.0188
Epoch 10/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0167 - mse: 0.0167
Epoch 11/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0150 - mse: 0.0150
Epoch 12/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0138 - mse: 0.0138
Epoch 13/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0130 - mse: 0.0130
Epoch 14/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0123 - mse: 0.0123
Epoch 15/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0118 - mse: 0.0118
Epoch 16/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0115 - mse: 0.0115
Epoch 17/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0114 - mse: 0.0114
Epoch 18/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0112 - mse: 0.0112
Epoch 19/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 20/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 21/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 22/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 23/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 24/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0111 - mse: 0.0111
Epoch 25/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0110 - mse: 0.0110
Epoch 26/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0103 - mse: 0.0103
Epoch 27/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0095 - mse: 0.0095
Epoch 28/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0085 - mse: 0.0085
Epoch 29/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0078 - mse: 0.0078
Epoch 30/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0073 - mse: 0.0073
Epoch 31/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0067 - mse: 0.0067
Epoch 32/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0065 - mse: 0.0065
Epoch 33/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0062 - mse: 0.0062
Epoch 34/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0062 - mse: 0.0062
Epoch 35/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0061 - mse: 0.0061
Epoch 36/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0059 - mse: 0.0059
Epoch 37/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0058 - mse: 0.0058
Epoch 38/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0058 - mse: 0.0058
Epoch 39/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0057 - mse: 0.0057
Epoch 40/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0058 - mse: 0.0058
Epoch 41/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 42/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 43/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 44/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 45/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 46/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 47/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 48/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 49/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 50/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 51/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0056 - mse: 0.0056
Epoch 52/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 53/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 54/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 55/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 56/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 57/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 58/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 59/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 60/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 61/100
34/34 [==============================] - 0s 3ms/step - loss: 0.0055 - mse: 0.0055
Epoch 62/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 63/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 64/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 65/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 66/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 67/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 68/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 69/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 70/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 71/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 72/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 73/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 74/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 75/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 76/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 77/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 78/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 79/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 80/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 81/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 82/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 83/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 84/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 85/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 86/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 87/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0053 - mse: 0.0053
Epoch 88/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0055 - mse: 0.0055
Epoch 89/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0053 - mse: 0.0053
Epoch 90/100
34/34 [==============================] - 0s 3ms/step - loss: 0.0053 - mse: 0.0053
Epoch 91/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 92/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0053 - mse: 0.0053
Epoch 93/100
34/34 [==============================] - 0s 3ms/step - loss: 0.0053 - mse: 0.0053
Epoch 94/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 95/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 96/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0053 - mse: 0.0053
Epoch 97/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 98/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 99/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054
Epoch 100/100
34/34 [==============================] - 0s 2ms/step - loss: 0.0054 - mse: 0.0054

In [19]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_pred,y_test))

0.004453657927778903

The minimum error is 0.004